spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-resources

  profiles:
    active: native

server:
  port: 8888
